export const FLUXOGRAMA_DATA = [
    { id: '1.0', task: 'CONTATO COM O CLIENTE', assign: 'Comercial / Diretor', obs: '' },
    { id: '1.1', task: 'Ligações diárias e reuniões de prospecção', assign: 'Comercial', obs: '' },
    { id: '1.2', task: 'Ata de reunião e início das tratativas', assign: 'Comercial', obs: '' },
    { id: '1.3', task: 'Identificação do decisor e mapeamento de stakeholders', assign: 'Comercial', obs: '' },
    { id: '2.0', task: 'ENTENDIMENTO DA DEMANDA', assign: 'Engenheiro', obs: '' },
    { id: '2.1', task: 'Levantamento detalhado do escopo com o cliente', assign: 'Engenheiro', obs: '' },
    { id: '2.2', task: 'Visita técnica preliminar ao terreno/local', assign: 'Engenheiro', obs: '' },
    { id: '2.3', task: 'Registro fotográfico e croqui de campo', assign: 'Engenheiro', obs: '' },
    { id: '2.4', task: 'Engenheiro envia relatório preliminar ao Diretor', assign: 'Engenheiro', obs: '⛔ Aprovação para prosseguir' },
    { id: '3.0', task: 'ANÁLISE CRÍTICA DOS PROJETOS', assign: 'Engenheiro', obs: '' },
    { id: '3.1', task: 'Recebimento e conferência dos projetos (Arq, Est, Hid, Ele)', assign: 'Engenheiro', obs: '' },
    { id: '3.2', task: 'Compatibilização entre disciplinas', assign: 'Engenheiro', obs: '' },
    { id: '3.3', task: 'Lista de pendências e inconformidades → devolver ao projetista', assign: 'Engenheiro', obs: '' },
    { id: '3.4', task: 'Parecer técnico apresentado ao Diretor', assign: 'Engenheiro', obs: '⛔ Aprovação para orçar' },
    { id: '4.0', task: 'DESENVOLVIMENTO DO ORÇAMENTO', assign: 'Engenheiro / Orçamentista', obs: '' },
    { id: '4.1', task: 'Levantamento quantitativo por disciplina', assign: 'Orçamentista', obs: '' },
    { id: '4.2', task: 'Composição de custos unitários (SINAPI / TCPO / base própria)', assign: 'Orçamentista', obs: '' },
    { id: '4.3', task: 'Cotação com fornecedores e empreiteiros', assign: 'Compras', obs: '' },
    { id: '4.4', task: 'Planilha de custos diretos + indiretos + BDI', assign: 'Orçamentista', obs: '' },
    { id: '4.5', task: 'Cronograma físico-financeiro preliminar', assign: 'Engenheiro', obs: '' },
    { id: '4.6', task: 'Diretor define margem de lucro e aprova orçamento', assign: 'Engenheiro', obs: '⛔ Aprovação da margem' },
    { id: '5.0', task: 'VISITA TÉCNICA À OBRA', assign: 'Engenheiro', obs: '' },
    { id: '5.1', task: 'Validação do orçamento in loco', assign: 'Engenheiro', obs: '' },
    { id: '5.2', task: 'Conferência de acessos, logística e condições do terreno', assign: 'Engenheiro', obs: '' },
    { id: '5.3', task: 'Identificação de riscos não previstos', assign: 'Engenheiro', obs: '' },
    { id: '6.0', task: 'REAJUSTE DO ORÇAMENTO', assign: 'Orçamentista', obs: '' },
    { id: '6.1', task: 'Incorporação das pendências de campo', assign: 'Orçamentista', obs: '' },
    { id: '6.2', task: 'Atualização de quantitativos e custos', assign: 'Orçamentista', obs: '' },
    { id: '6.3', task: 'Versão final do orçamento aprovada pelo Diretor', assign: 'Orçamentista', obs: '⛔ Aprovação para enviar ao cliente' },
    { id: '7.0', task: 'PROPOSTA COMERCIAL E NEGOCIAÇÃO', assign: 'Comercial / Diretor', obs: '' },
    { id: '7.1', task: 'Apresentação formal da proposta ao cliente', assign: 'Comercial', obs: '' },
    { id: '7.2', task: 'Rodadas de negociação (escopo, prazo, preço, pagamento)', assign: 'Diretor', obs: '' },
    { id: '7.3', task: 'Registro de todas as alterações em ata', assign: 'Comercial', obs: '' },
    { id: '8.0', task: 'ASSINATURA DO CONTRATO', assign: 'Jurídico / Diretor', obs: '' },
    { id: '8.1', task: 'Redação do contrato (escopo, prazos, multas, condições)', assign: 'Jurídico', obs: '' },
    { id: '8.2', task: 'Revisão jurídica', assign: 'Jurídico', obs: '' },
    { id: '8.3', task: 'Assinatura e emissão de ART/RRT', assign: 'Diretor / Engenheiro', obs: '' },
    { id: '8.4', task: 'Diretor designa formalmente o Engenheiro Residente', assign: 'Diretor', obs: '⚡ Delegação formal' },
    { id: '9.0', task: 'MOBILIZAÇÃO', assign: 'Engenheiro Residente', obs: '' },
    { id: '9.1', task: 'Montagem do canteiro (tapumes, barracão, banheiros, almoxarifado)', assign: 'Eng. Residente', obs: '' },
    { id: '9.2', task: 'Ligações provisórias (água, luz, esgoto)', assign: 'Eng. Residente', obs: '' },
    { id: '9.3', task: 'Contratação e integração de equipes (mão de obra + SST)', assign: 'Eng. Residente / RH', obs: '' },
    { id: '9.4', task: 'Compra inicial de materiais e equipamentos', assign: 'Compras', obs: '' },
    { id: '9.5', task: 'Cadastro da obra no sistema de gestão de tarefas', assign: 'Eng. Residente', obs: '' },
    { id: '10.0', task: 'PLANEJAMENTO EXECUTIVO', assign: 'Engenheiro Residente', obs: '' },
    { id: '10.1', task: 'Destrinchar cronograma em tarefas semanais e diárias', assign: 'Eng. Residente', obs: '' },
    { id: '10.2', task: 'Definição de frentes de serviço e responsáveis', assign: 'Eng. Residente', obs: '' },
    { id: '10.3', task: 'Linha de base do cronograma aprovada pelo Diretor', assign: 'Eng. Residente', obs: '⛔ Marco Zero da Obra' },
    { id: '11.0', task: 'EXECUÇÃO DA OBRA', assign: 'Engenheiro Residente', obs: '' },
    { id: '11.1', task: 'Abertura do Diário de Obra (RDO) diário', assign: 'Eng. Residente', obs: '' },
    { id: '11.2', task: 'Execução: Fundação → Estrutura → Alvenaria → Instalações → Acabamento', assign: 'Eng. Residente', obs: '' },
    { id: '11.3', task: 'Engenheiro cobra tarefas diárias da equipe em obra', assign: 'Eng. Residente', obs: 'Gestão operacional diária' },
    { id: '11.4', task: 'Controle de qualidade (FVS - Fichas de Verificação de Serviço)', assign: 'Eng. Residente', obs: '' },
    { id: '11.5', task: 'Gestão de SST: DDS diário, EPIs, fiscalização', assign: 'TST / Eng. Residente', obs: '' },
    { id: '12.0', task: 'CONTROLE E COBRANÇA PELA DIRETORIA (SEMANAL)', assign: 'Diretor', obs: '' },
    { id: '12.1', task: 'Reunião semanal de status: avanço físico x financeiro', assign: 'Eng. Residente', obs: '📊 Dashboard de KPIs' },
    { id: '12.2', task: 'Diretor cobra resultados dos blocos grandes', assign: 'Diretor', obs: 'Ex: \'Fundação 100%?\'' },
    { id: '12.3', task: 'Se desvio: Engenheiro apresenta plano de ação', assign: 'Eng. Residente', obs: 'Prazo para correção' },
    { id: '12.4', task: 'Diretor redistribui recursos entre obras se necessário', assign: 'Diretor', obs: 'Visão multi-obras' },
    { id: '13.0', task: 'GESTÃO DE SUPRIMENTOS', assign: 'Compras / Eng. Residente', obs: '' },
    { id: '13.1', task: 'Pedidos de compra conforme cronograma de suprimentos', assign: 'Compras', obs: '' },
    { id: '13.2', task: 'Recebimento, conferência e armazenamento no canteiro', assign: 'Almoxarife', obs: '' },
    { id: '13.3', task: 'Controle de estoque e prevenção de desperdício', assign: 'Almoxarife', obs: '' },
    { id: '14.0', task: 'MEDIÇÕES E FATURAMENTO', assign: 'Engenheiro / Financeiro', obs: '' },
    { id: '14.1', task: 'Apontamento de medição dos serviços executados', assign: 'Eng. Residente', obs: '' },
    { id: '14.2', task: 'Boletim de medição com fotos e memória de cálculo', assign: 'Eng. Residente', obs: '' },
    { id: '14.3', task: 'Diretor/Financeiro valida e envia ao cliente', assign: 'Financeiro', obs: '⛔ Aprovação de faturamento' },
    { id: '14.4', task: 'Emissão de NF e acompanhamento do pagamento', assign: 'Financeiro', obs: '' },
    { id: '15.0', task: 'ADITIVOS E REAJUSTES', assign: 'Engenheiro / Diretor', obs: '' },
    { id: '15.1', task: 'Identificação de serviços extras ou mudanças de escopo', assign: 'Eng. Residente', obs: '' },
    { id: '15.2', task: 'Engenheiro monta planilha → Diretor negocia com cliente', assign: 'Eng. Residente', obs: '⛔ Negociação direta' },
    { id: '15.3', task: 'Formalização do aditivo contratual', assign: 'Jurídico', obs: '' },
    { id: '16.0', task: 'RETA FINAL E ACABAMENTOS', assign: 'Engenheiro Residente', obs: '' },
    { id: '16.1', task: 'Checklist de pendências de acabamento', assign: 'Eng. Residente', obs: '' },
    { id: '16.2', task: 'Testes e comissionamento (hidráulico, elétrico, incêndio)', assign: 'Eng. Residente', obs: '' },
    { id: '16.3', task: 'Vistorias internas antes de chamar o cliente', assign: 'Eng. Residente', obs: '' },
    { id: '17.0', task: 'ENTREGA DA OBRA', assign: 'Engenheiro / Diretor', obs: '' },
    { id: '17.1', task: 'Vistoria conjunta com o cliente', assign: 'Eng. Residente', obs: '' },
    { id: '17.2', task: 'Correção de pendências (punch list)', assign: 'Eng. Residente', obs: '' },
    { id: '17.3', task: 'Entrega do As-Built, manuais e garantias', assign: 'Eng. Residente', obs: '' },
    { id: '17.4', task: 'Assinatura do Termo de Recebimento Definitivo', assign: 'Diretor / Cliente', obs: '' },
    { id: '18.0', task: 'DESMOBILIZAÇÃO', assign: 'Engenheiro Residente', obs: '' },
    { id: '18.1', task: 'Retirada de equipamentos e materiais sobressalentes', assign: 'Eng. Residente', obs: '' },
    { id: '18.2', task: 'Desmontagem do canteiro', assign: 'Eng. Residente', obs: '' },
    { id: '18.3', task: 'Rescisão/remanejamento de contratos de mão de obra', assign: 'RH', obs: '' },
    { id: '19.0', task: 'PÓS-OBRA E GARANTIA', assign: 'Engenheiro / Diretor', obs: '' },
    { id: '19.1', task: 'Atendimento a chamados de garantia', assign: 'Eng. Residente', obs: '5 anos estrutural / 1 ano acabamento' },
    { id: '19.2', task: 'Feedback com o cliente para melhoria contínua', assign: 'Comercial', obs: '' },
    { id: '19.3', task: 'Fechamento financeiro da obra', assign: 'Financeiro', obs: '📊 Lucro/Prejuízo final' },
    { id: '20.0', task: 'RETROALIMENTAÇÃO', assign: 'Diretor', obs: '' },
    { id: '20.1', task: 'Lições aprendidas registradas', assign: 'Eng. Residente', obs: '' },
    { id: '20.2', task: 'Atualização da base de custos da empresa', assign: 'Orçamentista', obs: '' },
    { id: '20.3', task: 'Avaliação de desempenho do Engenheiro pelo Diretor', assign: 'Diretor', obs: '📋 Avaliação formal' },
];
